# Generated by Django 5.2.6 on 2025-12-06 04:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicados', '0001_initial'),
        ('residentes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComunicadoResidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('leído', 'Leído')], default='enviado', max_length=20)),
                ('comunicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='comunicados.comunicado')),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicados_recibidos', to='residentes.residente')),
            ],
        ),
    ]
