# Generated by Django 5.2.6 on 2025-09-08 07:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
        ('residentes', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia')], max_length=20)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='reclamos/adjuntos/')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('abierto', 'Abierto'), ('resuelto', 'Resuelto')], default='pendiente', max_length=20)),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamos_asignados', to='empleados.empleado')),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamos', to='residentes.residente')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ronda', 'Ronda'), ('incidente', 'Incidente'), ('reporte', 'Reporte')], max_length=20)),
                ('origen', models.CharField(choices=[('seguridad', 'Seguridad'), ('residente', 'Residente')], max_length=20)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('ubicacion', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('resuelto', 'Resuelto')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_resueltos', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_seguridad', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
