# Generated by Django 5.2.6 on 2025-12-18 00:01

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
        ('residentes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_persona', models.CharField(choices=[('Residente', 'Residente'), ('Visitante', 'Visitante'), ('Empleado', 'Empleado'), ('Proveedor', 'Proveedor'), ('Otro', 'Otro')], max_length=50)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('ci', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula de Identidad')),
                ('motivo', models.TextField(blank=True, null=True)),
                ('tipo_acceso', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], max_length=10)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('foto', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_acceso', to='empleados.empleado')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_de_acceso', to=settings.AUTH_USER_MODEL)),
                ('residente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_acceso', to='residentes.residente')),
            ],
            options={
                'verbose_name': 'Registro de Acceso',
                'verbose_name_plural': 'Registros de Accesos',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
