# Generated by Django 5.2.6 on 2025-09-08 15:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('informativa', 'Informativa'), ('alerta', 'Alerta'), ('recordatorio', 'Recordatorio')], max_length=20)),
                ('ruta', models.CharField(blank=True, max_length=255, null=True)),
                ('leida', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tipo_residente', models.CharField(help_text='Ej: Propietario, Inquilino', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text="Ej: 'A-101'", max_length=50, unique=True)),
                ('placa', models.CharField(blank=True, max_length=20, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('capacidad', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(default='activa', max_length=20)),
                ('personas_por_unidad', models.PositiveIntegerField(default=1)),
                ('tiene_mascotas', models.BooleanField(default=False)),
                ('vehiculos', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_visitante', models.CharField(max_length=255)),
                ('ci_visitante', models.CharField(max_length=20)),
                ('placa_vehiculo', models.CharField(blank=True, max_length=15, null=True)),
                ('motivo', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('codigo', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En Curso'), ('finalizada', 'Finalizada')], default='pendiente', max_length=20)),
                ('hora_entrada', models.DateTimeField(blank=True, null=True)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
